import { useEffect, useMemo, useRef } from 'react'
import { Link } from 'react-router-dom'
import { CountUp, ParticleField, Reveal } from './ui'

const STATS = [
  { value: 0.000098, decimals: 0, display: '≈10%', label: 'Share of global electricity generated by nuclear power' },
  { value: 95, decimals: 0, display: '≈95%', label: 'Of mined uranium is unused in today’s once-through fuel cycle' },
  { value: 100, decimals: 0, display: '100%', label: 'Of licensed waste streams are characterised before classification' },
  { value: 1000000, decimals: 0, display: '1M yr', label: 'Design horizon of a geological repository' },
]

function ReactorCore() {
  return (
    <svg viewBox="0 0 400 400" className="h-full w-full" aria-hidden="true">
      <defs>
        <radialGradient id="coreGlow">
          <stop offset="0%" stopColor="#9df7ff" stopOpacity="0.85" />
          <stop offset="45%" stopColor="#38f0ff" stopOpacity="0.25" />
          <stop offset="100%" stopColor="#38f0ff" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="ringGrad" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#38f0ff" />
          <stop offset="100%" stopColor="#7c5cff" />
        </linearGradient>
      </defs>

      <circle cx="200" cy="200" r="150" fill="url(#coreGlow)" />

      {[120, 150, 175].map((r, i) => (
        <circle
          key={r}
          cx="200"
          cy="200"
          r={r}
          fill="none"
          stroke="url(#ringGrad)"
          strokeWidth={i === 2 ? 0.8 : 1.2}
          opacity={0.55 - i * 0.14}
          strokeDasharray={i === 1 ? '4 10' : undefined}
        >
          <animateTransform
            attributeName="transform"
            type="rotate"
            from={`0 200 200`}
            to={`360 200 200`}
            dur={`${28 + i * 14}s`}
            repeatCount="indefinite"
          />
        </circle>
      ))}

      {/* orbiting particles = fission tracks */}
      {[0, 60, 120, 180, 240, 300].map((deg, i) => (
        <g key={deg}>
          <circle r="4" fill="#b6ff3d">
            <animateMotion
              dur={`${9 + i}s`}
              repeatCount="indefinite"
              path="M 200 200 m -150 0 a 150 150 0 1 1 300 0 a 150 150 0 1 1 -300 0"
              rotate="auto"
            />
          </circle>
        </g>
      ))}

      <circle cx="200" cy="200" r="34" fill="#38f0ff" opacity="0.18" />
      <circle cx="200" cy="200" r="22" fill="#9df7ff">
        <animate attributeName="r" values="20;24;20" dur="3.4s" repeatCount="indefinite" />
      </circle>
    </svg>
  )
}

export default function Hero() {
  const ref = useRef<HTMLElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const onMove = (e: PointerEvent) => {
      const r = el.getBoundingClientRect()
      el.style.setProperty('--px', `${((e.clientX - r.left) / r.width - 0.5).toFixed(3)}`)
      el.style.setProperty('--py', `${((e.clientY - r.top) / r.height - 0.5).toFixed(3)}`)
    }
    el.addEventListener('pointermove', onMove)
    return () => el.removeEventListener('pointermove', onMove)
  }, [])

  const stats = useMemo(() => STATS, [])

  return (
    <section
      ref={ref}
      className="relative isolate overflow-hidden pt-20 pb-16 md:pt-28 md:pb-24"
    >
      <ParticleField />
      <div className="glow glow-a animate-drift" aria-hidden="true" />
      <div className="glow glow-b animate-drift [animation-delay:-9s]" aria-hidden="true" />

      {/* fine grid */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 -z-10 opacity-[0.16]"
        style={{
          backgroundImage:
            'linear-gradient(#1c2942 1px, transparent 1px), linear-gradient(90deg, #1c2942 1px, transparent 1px)',
          backgroundSize: '56px 56px',
          maskImage: 'radial-gradient(ellipse 80% 60% at 50% 30%, #000 40%, transparent 100%)',
        }}
      />

      <div className="wrap grid items-center gap-12 lg:grid-cols-[1.15fr_0.85fr]">
        <div>
          <Reveal>
            <p className="kicker">Educational resource · Radioactive materials</p>
          </Reveal>
          <Reveal delay={80}>
            <h1 className="mt-5 text-4xl leading-[1.05] font-semibold tracking-tight text-white sm:text-5xl lg:text-[3.6rem]">
              Nuclear Waste
              <br />
              Management <span className="grad">&amp; Sustainable Solutions</span>
            </h1>
          </Reveal>
          <Reveal delay={160}>
            <p className="mt-6 max-w-xl text-[1.02rem] leading-relaxed text-slate-300">
              What nuclear waste actually is, where it comes from, how it is handled safely today —
              and how advanced science is turning residue into resources, from uranium recovery to
              waste-to-heat and beyond.
            </p>
          </Reveal>

          <Reveal delay={240}>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link to="/cycle" className="btn btn-primary">
                Explore the management cycle
                <svg viewBox="0 0 24 24" aria-hidden="true">
                  <path d="M5 12h14M13 6l6 6-6 6" />
                </svg>
              </Link>
              <Link to="/fundamentals" className="btn btn-ghost">
                Start with the basics
              </Link>
            </div>
          </Reveal>

          <Reveal delay={320}>
            <dl className="mt-12 grid grid-cols-2 gap-x-6 gap-y-7 border-t border-edge/70 pt-8 lg:grid-cols-4">
              {stats.map((s) => (
                <div key={s.label}>
                  <dt className="sr-only">{s.label}</dt>
                  <dd>
                    <span className="block font-mono text-2xl font-medium text-plasma tabular-nums">
                      <CountUp to={s.value} decimals={s.decimals} />
                    </span>
                    <span className="mt-1.5 block text-[0.72rem] leading-snug text-slate-400">
                      {s.label}
                    </span>
                  </dd>
                </div>
              ))}
            </dl>
          </Reveal>
        </div>

        <Reveal delay={200} className="relative hidden lg:block">
          <div className="relative mx-auto aspect-square max-w-[26rem]">
            <div className="absolute inset-8 rounded-full border border-plasma/15" />
            <div className="animate-spin-slow absolute inset-0 rounded-full border border-dashed border-plasma/20" />
            <div className="absolute inset-16 rounded-full border border-aurora/15" />
            <ReactorCore />
            <div className="absolute inset-x-0 -bottom-2 flex flex-wrap justify-center gap-2 font-mono text-[0.6rem] tracking-widest text-slate-500 uppercase">
              <span className="rounded-full border border-edge px-2.5 py-1">Fission</span>
              <span className="rounded-full border border-edge px-2.5 py-1">Containment</span>
              <span className="rounded-full border border-edge px-2.5 py-1">Reuse</span>
              <span className="rounded-full border border-edge px-2.5 py-1">Disposal</span>
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  )
}
